import { CFG } from '../shared/core.js';
import { Jogo } from './engine.js';
import { tg } from './tg.js';
const tela = document.querySelector('#tela'); const fmt = n => Math.floor(n || 0).toLocaleString('pt-BR'); let aba = 'batalha';
const toast = msg => { const e = document.querySelector('#toast'); e.textContent = msg; e.classList.add('show'); setTimeout(() => e.classList.remove('show'), 2200); };
function hud() { const p = Jogo.projetar(); if (!p) return; document.querySelector('#ouro').textContent = fmt(p.ouro); document.querySelector('#energia').textContent = `${fmt(p.energia)}/${fmt(p.energia_max)}`; document.querySelector('#nivel').textContent = p.nivel; }
function batalha() { const p = Jogo.projetar(); return `<section class="hero"><h1>Nível ${p.nivel} · ${fmt(p.xp)} XP</h1><p>Toque no alvo para ganhar ouro</p><button class="alvo" id="alvo">⚔️</button><div class="energia-bar"><i style="width:${Math.min(100, p.energia / p.energia_max * 100)}%"></i></div><p class="muted">${fmt(p.energia)} / ${fmt(p.energia_max)} energia · ${p.dano} ouro por clique</p></section><h2>Forja</h2><div class="grid">${p.forja.map(u => `<article class="card"><div class="row"><b>${u.icone} ${u.nome}</b><span>Nv. ${u.nivel}</span></div><p class="muted">Custo: ${fmt(u.custo)} 🪙</p><button data-up="${u.chave}" ${u.nivel >= u.max ? 'disabled' : ''}>Forjar</button></article>`).join('')}</div>`; }
function stakes() { const p = Jogo.projetar(); return `<h2>Stakes ativos</h2>${p.stakes.length ? p.stakes.map(s => `<article class="card"><div class="row"><b>${s.icone} ${s.nome}</b><b class="gold">${fmt(s.total)} 🪙</b></div><div class="progress"><i style="width:${s.pct * 100}%"></i></div><p class="muted">${s.cheio ? 'Pronto para coletar' : `${Math.ceil(s.faltaMs / 3600000)}h restantes`}</p><button data-coletar="${s.id}">Coletar</button></article>`).join('') : '<p class="muted">Nenhum stake ativo.</p>'}<h2>Novos stakes</h2><div class="grid">${Object.entries(CFG.ZONAS).map(([id, z]) => `<article class="card"><b>${z.icone} ${z.nome}</b><p class="muted">Mínimo: ${z.min} 🪙</p><button data-zona="${id}">Investir ${z.min}</button></article>`).join('')}</div>`; }
function missoes() { const p = Jogo.projetar(); return `<h2>Missões</h2>${p.missoes.map(m => `<article class="card"><div class="row"><b>${m.nome}</b><span class="gold">+${fmt(m.ouro)} 🪙</span></div><p class="muted">${m.desc} · ${m.atual}/${m.meta}</p><div class="progress"><i style="width:${m.pct * 100}%"></i></div><button data-missao="${m.id}" ${!m.completa || m.coletada ? 'disabled' : ''}>${m.coletada ? 'Resgatada' : 'Resgatar'}</button></article>`).join('')}`; }
export const UI = { montar() { render(); setInterval(hud, 100); setInterval(() => { if (aba !== 'batalha') render(); }, 1000); document.querySelector('#abas').addEventListener('click', e => { const b = e.target.closest('[data-aba]'); if (!b) return; aba = b.dataset.aba; document.querySelectorAll('#abas button').forEach(x => x.classList.toggle('ativo', x === b)); render(); }); tela.addEventListener('click', async e => { if (e.target.closest('#alvo')) { if (Jogo.clicar()) { tg.haptic('light'); const f = document.createElement('span'); f.className = 'float'; f.textContent = `+${Jogo.projetar().dano}`; f.style.left = `${e.clientX}px`; f.style.top = `${e.clientY}px`; document.body.append(f); setTimeout(() => f.remove(), 700); } return; } const b = e.target.closest('[data-up],[data-zona],[data-coletar],[data-missao]'); if (!b) return; await Jogo.acao(b.dataset.up ? 'upgrade' : b.dataset.zona ? 'stake_criar' : b.dataset.coletar ? 'stake_coletar' : 'missao_coletar', b.dataset.up ? { chave: b.dataset.up } : b.dataset.zona ? { zona: b.dataset.zona, valor: CFG.ZONAS[b.dataset.zona].min } : b.dataset.coletar ? { id: b.dataset.coletar } : { id: b.dataset.missao }); render(); }); }, render() { tela.innerHTML = aba === 'batalha' ? batalha() : aba === 'stake' ? stakes() : missoes(); hud(); }, toast };
Jogo.onErro = toast;
