CREATE TABLE IF NOT EXISTS jogadores (tg_id INTEGER PRIMARY KEY, ouro REAL NOT NULL DEFAULT 0, xp REAL NOT NULL DEFAULT 0, energia REAL NOT NULL DEFAULT 500, upgrades TEXT NOT NULL DEFAULT '{}', stakes TEXT NOT NULL DEFAULT '[]', missoes TEXT NOT NULL DEFAULT '{}', cliques_dia INTEGER NOT NULL DEFAULT 0, dia TEXT NOT NULL, ts INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS ledger (id INTEGER PRIMARY KEY AUTOINCREMENT, tg_id INTEGER NOT NULL, delta REAL NOT NULL, motivo TEXT NOT NULL, ts INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_ledger ON ledger(tg_id, ts);
