import { CFG, custoUpgrade, nivelPorXp, rendimento, simular, stats } from './core.js';
export function novoJogador(id, agora) { return { tg_id: Number(id), ouro: 0, xp: 0, energia: 500, upgrades: {}, stakes: [], missoes: { prog: {}, ok: [] }, cliques_dia: 0, dia: new Date(agora).toISOString().slice(0, 10), ts: agora }; }
const clone = v => JSON.parse(JSON.stringify(v));
function normalizar(j, agora) { j.missoes ||= { prog: {}, ok: [] }; j.missoes.prog ||= {}; j.missoes.ok ||= []; if (j.dia !== new Date(agora).toISOString().slice(0, 10)) { j.dia = new Date(agora).toISOString().slice(0, 10); j.cliques_dia = 0; } return j; }
export function processar(estado, acao, dados = {}, agora) { const j = normalizar(clone(estado), agora); const ledger = []; const aplicar = cliques => { const r = simular(j, agora, cliques); j.ouro = r.ouro; j.xp = r.xp; j.energia = r.energia; j.ts = agora; j.cliques_dia += r.efetivos; j.missoes.prog.cliques = (j.missoes.prog.cliques || 0) + r.efetivos; return r; }; const erro = msg => ({ erro: msg }); aplicar(dados.cliques);
  if (acao === 'sync') return { j, ledger };
  if (acao === 'stake_criar') { const z = CFG.ZONAS[dados.zona]; const valor = Math.floor(Number(dados.valor)); if (!z) return erro('Zona inválida'); if (!Number.isInteger(valor) || valor < z.min) return erro(`Valor mínimo: ${z.min}`); if (j.stakes.length >= CFG.MAX_STAKES) return erro('Limite de stakes atingido'); if (j.ouro < valor) return erro('Ouro insuficiente'); j.ouro -= valor; j.stakes.push({ id: `${agora}-${Math.random().toString(36).slice(2)}`, zona: dados.zona, valor, inicio: agora }); j.missoes.prog.stakes = (j.missoes.prog.stakes || 0) + 1; ledger.push({ delta: -valor, motivo: 'stake_criar' }); }
  else if (acao === 'stake_coletar') { const i = j.stakes.findIndex(s => s.id === dados.id); if (i < 0) return erro('Stake não encontrado'); const total = rendimento(j.stakes[i], agora).total; j.stakes.splice(i, 1); j.ouro += total; j.missoes.prog.coletas = (j.missoes.prog.coletas || 0) + 1; ledger.push({ delta: total, motivo: 'stake' }); }
  else if (acao === 'upgrade') { const u = CFG.UPGRADES[dados.chave]; const nivel = j.upgrades[dados.chave] || 0; if (!u || nivel >= u.max) return erro('Upgrade indisponível'); const custo = custoUpgrade(dados.chave, nivel); if (j.ouro < custo) return erro('Ouro insuficiente'); j.ouro -= custo; j.upgrades[dados.chave] = nivel + 1; j.missoes.prog.upgrades = (j.missoes.prog.upgrades || 0) + 1; ledger.push({ delta: -custo, motivo: 'upgrade' }); }
  else if (acao === 'missao_coletar') { const m = CFG.MISSOES.find(x => x.id === dados.id); const prog = j.missoes.prog[m?.tipo] || 0; if (!m || prog < m.meta || j.missoes.ok.includes(m.id)) return erro('Missão indisponível'); j.missoes.ok.push(m.id); j.ouro += m.ouro; ledger.push({ delta: m.ouro, motivo: 'missao' }); }
  else if (acao !== 'sync') return erro('Ação desconhecida');
  return { j, ledger };
}
export function estado(j, agora) { const st = stats(j.upgrades); return { ouro: j.ouro, xp: j.xp, energia: j.energia, upgrades: j.upgrades, ts: j.ts, agora, ...st, nivel: nivelPorXp(j.xp), stakes: j.stakes.map(s => ({ ...s, ...rendimento(s, agora), nome: CFG.ZONAS[s.zona].nome, icone: CFG.ZONAS[s.zona].icone })), forja: Object.entries(CFG.UPGRADES).map(([chave, u]) => ({ chave, ...u, nivel: j.upgrades[chave] || 0, custo: custoUpgrade(chave, j.upgrades[chave] || 0) })), missoes: CFG.MISSOES.map(m => ({ ...m, atual: j.missoes.prog[m.tipo] || 0, pct: Math.min(1, (j.missoes.prog[m.tipo] || 0) / m.meta), completa: (j.missoes.prog[m.tipo] || 0) >= m.meta, coletada: j.missoes.ok.includes(m.id) })) }; }
